import * as path from "path";
import { fileURLToPath } from "url";

export const protocol = "https://";

export const baseUrl = {
  api: "pokeapi.co/api/v2/",
  sprites: "raw.githubusercontent.com/PokeAPI/sprites/master/sprites/",
} as const;

const __dirname = path.dirname(fileURLToPath(import.meta.url));

/** Resolved path to the local PokeAPI JSON cache root (`localCache/<baseUrl.api>`). */
export const cacheBase = path.resolve(
  __dirname,
  "../../../server-cache",
  baseUrl.api,
);

export const endpointMap = {
  ability: "ability",
  berry: "berry",
  berryFirmness: "berry-firmness",
  berryFlavor: "berry-flavor",
  characteristic: "characteristic",
  contestEffect: "contest-effect",
  contestType: "contest-type",
  eggGroup: "egg-group",
  encounterCondition: "encounter-condition",
  encounterConditionValue: "encounter-condition-value",
  encounterMethod: "encounter-method",
  evolutionChain: "evolution-chain",
  evolutionTrigger: "evolution-trigger",
  gender: "gender",
  generation: "generation",
  growthRate: "growth-rate",
  item: "item",
  itemAttribute: "item-attribute",
  itemCategory: "item-category",
  itemFlingEffect: "item-fling-effect",
  itemPocket: "item-pocket",
  language: "language",
  location: "location",
  locationArea: "location-area",
  machine: "machine",
  move: "move",
  moveAilment: "move-ailment",
  moveBattleStyle: "move-battle-style",
  moveCategory: "move-category",
  moveDamageClass: "move-damage-class",
  moveLearnMethod: "move-learn-method",
  moveTarget: "move-target",
  nature: "nature",
  palParkArea: "pal-park-area",
  pokeathlonStat: "pokeathlon-stat",
  pokedex: "pokedex",
  pokemon: "pokemon",
  pokemonColor: "pokemon-color",
  pokemonForm: "pokemon-form",
  pokemonHabitat: "pokemon-habitat",
  pokemonLocationArea: "pokemon/:id/encounters",
  pokemonShape: "pokemon-shape",
  pokemonSpecies: "pokemon-species",
  region: "region",
  stat: "stat",
  superContestEffect: "super-contest-effect",
  type: "type",
  version: "version",
  versionGroup: "version-group",
} as const;

export const pokeApiResources = {
  ability: "https://pokeapi.co/api/v2/ability/",
  berry: "https://pokeapi.co/api/v2/berry/",
  "berry-firmness": "https://pokeapi.co/api/v2/berry-firmness/",
  "berry-flavor": "https://pokeapi.co/api/v2/berry-flavor/",
  characteristic: "https://pokeapi.co/api/v2/characteristic/",
  "contest-effect": "https://pokeapi.co/api/v2/contest-effect/",
  "contest-type": "https://pokeapi.co/api/v2/contest-type/",
  "egg-group": "https://pokeapi.co/api/v2/egg-group/",
  "encounter-condition": "https://pokeapi.co/api/v2/encounter-condition/",
  "encounter-condition-value":
    "https://pokeapi.co/api/v2/encounter-condition-value/",
  "encounter-method": "https://pokeapi.co/api/v2/encounter-method/",
  "evolution-chain": "https://pokeapi.co/api/v2/evolution-chain/",
  "evolution-trigger": "https://pokeapi.co/api/v2/evolution-trigger/",
  gender: "https://pokeapi.co/api/v2/gender/",
  generation: "https://pokeapi.co/api/v2/generation/",
  "growth-rate": "https://pokeapi.co/api/v2/growth-rate/",
  item: "https://pokeapi.co/api/v2/item/",
  "item-attribute": "https://pokeapi.co/api/v2/item-attribute/",
  "item-category": "https://pokeapi.co/api/v2/item-category/",
  "item-fling-effect": "https://pokeapi.co/api/v2/item-fling-effect/",
  "item-pocket": "https://pokeapi.co/api/v2/item-pocket/",
  language: "https://pokeapi.co/api/v2/language/",
  location: "https://pokeapi.co/api/v2/location/",
  "location-area": "https://pokeapi.co/api/v2/location-area/",
  machine: "https://pokeapi.co/api/v2/machine/",
  meta: "https://pokeapi.co/api/v2/meta/",
  move: "https://pokeapi.co/api/v2/move/",
  "move-ailment": "https://pokeapi.co/api/v2/move-ailment/",
  "move-battle-style": "https://pokeapi.co/api/v2/move-battle-style/",
  "move-category": "https://pokeapi.co/api/v2/move-category/",
  "move-damage-class": "https://pokeapi.co/api/v2/move-damage-class/",
  "move-learn-method": "https://pokeapi.co/api/v2/move-learn-method/",
  "move-target": "https://pokeapi.co/api/v2/move-target/",
  nature: "https://pokeapi.co/api/v2/nature/",
  "pal-park-area": "https://pokeapi.co/api/v2/pal-park-area/",
  "pokeathlon-stat": "https://pokeapi.co/api/v2/pokeathlon-stat/",
  pokedex: "https://pokeapi.co/api/v2/pokedex/",
  pokemon: "https://pokeapi.co/api/v2/pokemon/",
  "pokemon-color": "https://pokeapi.co/api/v2/pokemon-color/",
  "pokemon-form": "https://pokeapi.co/api/v2/pokemon-form/",
  "pokemon-habitat": "https://pokeapi.co/api/v2/pokemon-habitat/",
  "pokemon-shape": "https://pokeapi.co/api/v2/pokemon-shape/",
  "pokemon-species": "https://pokeapi.co/api/v2/pokemon-species/",
  region: "https://pokeapi.co/api/v2/region/",
  stat: "https://pokeapi.co/api/v2/stat/",
  "super-contest-effect": "https://pokeapi.co/api/v2/super-contest-effect/",
  type: "https://pokeapi.co/api/v2/type/",
  version: "https://pokeapi.co/api/v2/version/",
  "version-group": "https://pokeapi.co/api/v2/version-group/",
} as const;
